### ISSUE TITLE
How to change firmware list?

### ISSUE THREAD

**Issue by BluePygmyOwl** [DieBieEngineering/DieBieMS-Tool#6]
Hi,
I have made some changes to the DieBieMS-Firware for my BMS. As it now has to be seen as a different firmware, I gave it my own firware version number and name. Now I would like to use the DieBieMS-Tool to read my own DieBieMS-firmware, but obviously, the DieBieMS-Tool is not accepting my firmware as known and safe.

I opened all cpp / forms / header files, but can't seem to find the 'safe firmware number/name list'. Where can I change that?
Very much appreciated!

Thomas

**Comment by Peemouse** [comment]
Hi,
You need to add an `<enumNames>` with your FW version number here : 
https://github.com/DieBieEngineering/DieBieMS-Tool/blob/master/res/info.xml#L16

You also need to be sure that the de/serialization is the same both DBMS Tool and FW sides.
