### ISSUE TITLE
Installation issue 

### ISSUE THREAD

**Issue by raviatnunam** [DieBieEngineering/DieBieMS-Tool#7]
How to install DieBieMS tool on Windows machine? Is there direct installation files for Windows? If possible can you provide me some guide?

**Comment by Peemouse** [comment]
Go on the "Releases" tab and download the latest version. There is no installation to do. Just launch the .exe file.

**Comment by raviatnunam** [comment]
Yeah, Thank you i found it and forgot to close this issue.
